import { describe, expect, it } from 'vitest';
import {
  combineDiffs,
  resultToDiff,
  suggestionToDiff,
  toDiffFilename,
} from '../apps/web/src/lib/patch-export';
import type { PatchResult, PatchSuggestion } from '@ai-pr-reviewer/shared';

const DIFF_A = ['--- a/src/a.ts', '+++ b/src/a.ts', '@@ -1 +1 @@', '-a', '+b'].join(
  '\n',
);
const DIFF_B = ['--- a/src/b.ts', '+++ b/src/b.ts', '@@ -1 +1 @@', '-c', '+d'].join(
  '\n',
);

const suggestion: PatchSuggestion = {
  id: 'suggestion-1-guard-null',
  title: 'Guard null value',
  description: 'Adds a guard.',
  targetFindingIds: ['bug-1-null-check'],
  files: [
    {
      path: 'src/a.ts',
      previousPath: null,
      unifiedDiff: DIFF_A,
      additions: 1,
      deletions: 1,
    },
    {
      path: 'src/b.ts',
      previousPath: null,
      unifiedDiff: DIFF_B,
      additions: 1,
      deletions: 1,
    },
  ],
};

const result: PatchResult = {
  suggestions: [suggestion],
  generatedAt: '2026-01-03T00:00:00Z',
  disclaimer: 'Suggested patches only.',
};

describe('patch export tools', () => {
  it('combines multiple diffs into one patch body', () => {
    const combined = combineDiffs([DIFF_A, DIFF_B]);
    expect(combined).toContain('--- a/src/a.ts');
    expect(combined).toContain('--- a/src/b.ts');
    expect(combined.endsWith('\n')).toBe(true);
  });

  it('exports a single suggestion as a unified patch', () => {
    const diff = suggestionToDiff(suggestion);
    expect(diff).toContain('-a');
    expect(diff).toContain('+d');
    expect(diff).toContain('--- a/src/b.ts');
  });

  it('includes informational headers in the full result export', () => {
    const diff = resultToDiff(result);
    expect(diff).toContain('# Suggested patches generated by AI PR Reviewer');
    expect(diff).toContain('Suggested patches only.');
    expect(diff).toContain('2026-01-03T00:00:00Z');
    expect(diff).toContain('# --- Guard null value ---');
    expect(diff).toContain('--- a/src/a.ts');
  });

  it('sanitizes filenames for downloads', () => {
    expect(toDiffFilename('Guard the null value!')).toBe(
      'guard-the-null-value.diff',
    );
    expect(toDiffFilename('suggestion-1-guard-null')).toBe(
      'suggestion-1-guard-null.diff',
    );
    expect(toDiffFilename('already.diff')).toBe('already.diff');
    expect(toDiffFilename('???')).toBe('patch.diff');
  });
});
