import { Bug, FileCode2, Gauge, RefreshCw, ShieldAlert, Sparkles } from 'lucide-react';
import type { ComplexityNote, ReviewReport } from '@ai-pr-reviewer/shared';
import { FindingsSection } from '@/components/findings-section';
import { RiskScoreCard } from '@/components/risk-score-card';
import { Badge } from '@/components/ui/badge';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';

function ComplexitySection({ notes }: { notes: ComplexityNote[] }) {
  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-2">
          <Gauge />
          <CardTitle>Complexity Notes</CardTitle>
          <span className="rounded-full bg-muted px-2 py-0.5 text-xs font-medium text-muted-foreground">
            {notes.length}
          </span>
        </div>
        <CardDescription>
          Maintainability and readability observations
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {notes.length === 0 ? (
          <p className="text-sm text-muted-foreground">
            No notable complexity concerns detected.
          </p>
        ) : (
          notes.map((note) => (
            <article key={note.id} className="space-y-2 rounded-lg border p-4">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <Badge variant="secondary" className="capitalize">
                  {note.impact} impact
                </Badge>
                {note.file ? (
                  <span className="truncate font-mono text-xs text-muted-foreground">
                    {note.file}
                  </span>
                ) : null}
              </div>
              <h4 className="font-medium leading-snug">{note.title}</h4>
              <p className="text-sm leading-relaxed text-muted-foreground">
                {note.description}
              </p>
            </article>
          ))
        )}
      </CardContent>
    </Card>
  );
}

export function ReviewReport({ report }: { report: ReviewReport }) {
  return (
    <div className="space-y-6" data-testid="review-report">
      <div className="grid gap-6 lg:grid-cols-3">
        <Card className="lg:col-span-2">
          <CardHeader>
            <div className="flex items-center gap-2">
              <Sparkles />
              <CardTitle>Executive Summary</CardTitle>
            </div>
            <CardDescription>
              What this pull request does and how it reads overall
            </CardDescription>
          </CardHeader>
          <CardContent>
            <p className="whitespace-pre-wrap text-sm leading-relaxed">
              {report.summary}
            </p>
            <p className="mt-4 text-xs text-muted-foreground">
              Generated by {report.provider} · {report.model} ·{' '}
              {new Date(report.generatedAt).toLocaleString()}
            </p>
          </CardContent>
        </Card>

        <RiskScoreCard risk={report.risk} />
      </div>

      <FindingsSection
        title="Potential Bugs"
        description="Logic errors, edge cases, and correctness risks"
        icon={<Bug />}
        findings={report.bugs}
        emptyMessage="No potential bugs detected in the analyzed diff."
      />

      <FindingsSection
        title="Security Findings"
        description="Vulnerabilities and unsafe practices introduced or touched by this PR"
        icon={<ShieldAlert />}
        findings={report.security}
        emptyMessage="No security findings detected in the analyzed diff."
      />

      <FindingsSection
        title="Refactoring Suggestions"
        description="Structure, duplication, and readability improvements"
        icon={<RefreshCw />}
        findings={report.refactoring}
        emptyMessage="No refactoring suggestions for this pull request."
      />

      <ComplexitySection notes={report.complexity} />

      <p className="flex items-center justify-center gap-1.5 text-xs text-muted-foreground">
        <FileCode2 className="h-3.5 w-3.5" />
        Read-only analysis. No code, branches, or pull requests are modified.
      </p>
    </div>
  );
}
