import type { PatchResult, PatchSuggestion } from '@ai-pr-reviewer/shared';

export function combineDiffs(
  diffs: readonly string[],
): string {
  return `${diffs.map((diff) => diff.trimEnd()).join('\n\n')}\n`;
}

export function suggestionToDiff(suggestion: PatchSuggestion): string {
  return combineDiffs(suggestion.files.map((file) => file.unifiedDiff));
}

export function resultToDiff(result: PatchResult): string {
  const header = [
    '# Suggested patches generated by AI PR Reviewer',
    `# ${result.disclaimer}`,
    `# Generated at: ${result.generatedAt}`,
    '',
  ].join('\n');

  const body = result.suggestions
    .map(
      (suggestion) =>
        `# --- ${suggestion.title} ---\n${suggestionToDiff(suggestion)}`,
    )
    .join('\n');

  return `${header}\n${body}`;
}

export function toDiffFilename(baseName: string): string {
  const safe =
    baseName
      .toLowerCase()
      .replace(/[^a-z0-9._-]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 80) || 'patch';
  return safe.endsWith('.diff') ? safe : `${safe}.diff`;
}

export function downloadTextFile(filename: string, content: string): void {
  const blob = new Blob([content], {
    type: 'text/x-diff;charset=utf-8',
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
